# Generated by Django 4.2.6 on 2023-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prod',
            new_name='prodt',
        ),
        migrations.AddField(
            model_name='items',
            name='quan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
